name: handtalk
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera_android_camerax: ^0.6.8+2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  speech_to_text: ^7.0.0
  provider: ^6.1.2
  screenshot: ^3.0.0
  camera: ^0.11.0+2
  tflite_v2: ^1.0.0
  image: ^4.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Italic.ttf
          style: italic
  assets:
    - assets/logo.png
    - assets/model.tflite
    - assets/labels.txt
    - assets/gesture_recognition_label.txt
    - assets/gesture_recognition_model.tflite
    - assets/vocabulary_card.json
    - assets/abjad/A.jpeg
    - assets/abjad/B.jpeg
    - assets/abjad/C.jpeg
    - assets/abjad/D.jpeg
    - assets/abjad/E.jpeg
    - assets/abjad/F.jpeg
    - assets/abjad/G.jpeg
    - assets/abjad/H.jpeg
    - assets/abjad/I.jpeg
    - assets/abjad/J.jpeg
    - assets/abjad/K.jpeg
    - assets/abjad/L.jpeg
    - assets/abjad/M.jpeg
    - assets/abjad/N.jpeg
    - assets/abjad/O.jpeg
    - assets/abjad/P.jpeg
    - assets/abjad/Q.jpeg
    - assets/abjad/R.jpeg
    - assets/abjad/S.jpeg
    - assets/abjad/T.jpeg
    - assets/abjad/U.jpeg
    - assets/abjad/V.jpeg
    - assets/abjad/W.jpeg
    - assets/abjad/X.jpeg
    - assets/abjad/Y.jpeg
    - assets/abjad/Z.jpeg
  